### ISSUE TITLE
Collect events - maxEvents spec allows 0

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/ya-client#28]
It doesn't make sense to query 0 events, but I implemented it like this since spec requires ;)
Needs changes in spec

**Comment by prekucki** [comment]
```yaml
name: maxEvents
description: >
  Maximum number of events that server should return at once.
required: false
in: query
schema:
      type: integer
      format: int32
      default: 10
      minimum: 1
      maximum: 100
```
